name: Dependency Review

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: critical # Gagal jika ada kerentanan kritis
        allow-licenses: MIT, Apache-2.0 # Izinkan hanya lisensi tertentu
        deny-licenses: GPL-3.0 # Tolak lisensi tertentu (opsional)
